services:
  chikahae-app:
    image: chikahae/server:latest
    container_name: chikahae-prod-app
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
    networks:
      - backend-bridge
    env_file:
      - .env
    # MySQL
  mysql:
    image: mysql:8.0
    container_name: chikahae-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-bridge

networks:
  backend-bridge:
    driver: bridge
